import { promises as fs } from "node:fs";
import path from "node:path";
import type { MentalModel } from "../core/types.js";
import type { Workspace } from "../config/workspace.js";

/**
 * Documentation generation (INSTRUCTIONS.md → "Documentación automática"). Produces
 * an architecture overview derived from the mental model. Written under the workspace
 * by default so it never clobbers the user's own `docs/`; the CLI can opt to emit it
 * into the repo when the user asks.
 */
export function renderArchitecture(model: MentalModel): string {
  const lines: string[] = [];
  lines.push(`# Architecture Overview`);
  lines.push(``);
  lines.push(`_Generated by Orgit on ${new Date().toISOString().slice(0, 10)}._`);
  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`- **Files:** ${model.totals.files}`);
  lines.push(`- **Lines of code:** ${model.totals.lines}`);
  lines.push(`- **Ecosystem:** ${model.signals.ecosystem}`);
  if (model.signals.packageManager) {
    lines.push(`- **Package manager:** ${model.signals.packageManager}`);
  }
  lines.push(``);
  lines.push(`## Languages`);
  lines.push(``);
  Object.entries(model.languages)
    .sort((a, b) => b[1] - a[1])
    .forEach(([lang, count]) => lines.push(`- ${lang}: ${count} file(s)`));
  lines.push(``);
  lines.push(`## Modules`);
  lines.push(``);
  Object.entries(model.modules)
    .sort((a, b) => b[1].length - a[1].length)
    .forEach(([mod, files]) => lines.push(`- **${mod}** — ${files.length} file(s)`));
  lines.push(``);
  lines.push(`## Build & Validation`);
  lines.push(``);
  const s = model.signals.scripts;
  lines.push(`- Build: ${s.build ? `\`${s.build}\`` : "_none detected_"}`);
  lines.push(`- Test: ${s.test ? `\`${s.test}\`` : "_none detected_"}`);
  lines.push(`- Lint: ${s.lint ? `\`${s.lint}\`` : "_none detected_"}`);
  lines.push(``);
  return lines.join("\n");
}

export async function writeArchitectureDoc(
  ws: Workspace,
  model: MentalModel,
  toRepo: boolean,
): Promise<string> {
  const content = renderArchitecture(model);
  const target = toRepo
    ? path.join(ws.root, "docs", "ARCHITECTURE.md")
    : path.join(ws.reportsDir, "ARCHITECTURE.md");
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, content, "utf8");
  return target;
}
