# If you set up sponsorship, uncomment the relevant line so GitHub shows a "Sponsor" button.
# github: [Gerijacki]
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
