import { promises as fs } from "node:fs";
import path from "node:path";
import { z } from "zod";
import type { MentalModel, Task, TaskResult } from "../core/types.js";
import type { ClaudeProvider } from "../providers/types.js";
import { completeJson } from "../providers/factory.js";
import { Git } from "../util/git.js";
import { validate } from "../validation/validate.js";
import { readFileSafe, fileExists, sha256 } from "../util/fsutil.js";

const EditResult = z.object({
  explanation: z.string(),
  edits: z
    .array(
      z.object({
        path: z.string(),
        /** Full replacement contents for the file. */
        content: z.string(),
      }),
    )
    .default([]),
});

const EXECUTE_SYSTEM = `You are Orgit's executor: a careful senior engineer applying ONE small, reversible
refactoring task. Rules:
- Preserve behaviour. Do NOT change functionality or public APIs unless the task explicitly requires it.
- Return the FULL new contents of each file you change. You must NOT modify any existing file that
  isn't listed for the task. To de-duplicate, PREFER extracting the shared logic into a NEW module
  (return its full contents, with correct relative import paths) rather than editing an existing
  shared file — you may create new files freely, but editing an unlisted existing file is not allowed.
- Make the smallest change that accomplishes the task. No unrelated edits, no reformatting churn.
- If the task cannot be done safely, return an empty edits array and explain why.`;

export interface ExecuteOptions {
  dryRun: boolean;
  /** Rendered learned conventions, so edits respect the project's house style. */
  conventions?: string;
}

/**
 * A task's edit, generated by Claude but not yet applied. Splitting generation from
 * application lets Orgit fan out the slow LLM calls for independent tasks in parallel
 * (Analyze + Modify), then apply/validate/commit them one at a time on the shared
 * working tree (Review + Verify + Finalize).
 */
export interface GeneratedEdit {
  taskId: string;
  /** In-scope edits (full replacement contents), or empty if the task was skipped. */
  edits: Array<{ path: string; content: string }>;
  explanation?: string;
  /** SHA-256 of each source file at generation time — used to detect staleness. */
  sourceHashes: Record<string, string>;
  /** Set when the task should be skipped (no files, no in-scope edits, or a failure). */
  skip?: string;
}

/**
 * Analyze + Modify (parallel-safe): read the task's files and ask Claude for a
 * concrete edit. Performs no git or filesystem writes, so many of these can run
 * concurrently.
 */
export async function generateEdit(
  model: MentalModel,
  task: Task,
  provider: ClaudeProvider,
  conventions?: string,
): Promise<GeneratedEdit> {
  const files: Array<{ path: string; content: string }> = [];
  const sourceHashes: Record<string, string> = {};
  const newFiles: string[] = [];
  for (const rel of task.files) {
    const content = await readFileSafe(model.root, rel);
    if (content !== null) {
      files.push({ path: rel, content });
      sourceHashes[rel] = sha256(content);
    } else {
      // A file the step will create — not an error, just not on disk yet.
      newFiles.push(rel);
    }
  }
  if (files.length === 0 && newFiles.length === 0) {
    return { taskId: task.id, edits: [], sourceHashes, skip: "task declares no target files" };
  }

  let edit: z.infer<typeof EditResult>;
  try {
    edit = await completeJson(provider, EditResult, {
      system: EXECUTE_SYSTEM,
      prompt: buildEditPrompt(task, files, newFiles, conventions),
      maxTokens: 16_000,
    });
  } catch (err) {
    return {
      taskId: task.id,
      edits: [],
      sourceHashes,
      skip: `edit generation failed: ${(err as Error).message}`,
    };
  }

  // Keep edits to the task's declared files, plus NEW files the refactor legitimately needs
  // (e.g. extracting shared logic into a new module for a de-duplication task). Reject only edits
  // that would modify an EXISTING file the task didn't declare — that preserves the "touch only
  // what you declared" invariant while letting extract-to-helper refactors succeed. Previously such
  // a new file was silently dropped while the rewritten files that imported it were kept, so every
  // dedup task left a dangling import, failed validation, and always rolled back.
  const scoped: Array<{ path: string; content: string }> = [];
  const outOfScope: string[] = [];
  for (const e of edit.edits) {
    if (task.files.includes(e.path)) {
      scoped.push(e);
    } else if (
      withinRepo(model.root, e.path) &&
      !(await fileExists(path.join(model.root, e.path)))
    ) {
      scoped.push(e); // a brand-new, in-repo file the model created for this task
    } else {
      outOfScope.push(e.path); // an existing file the task didn't declare (or an out-of-repo path)
    }
  }
  // Never apply only PART of a coherent edit. If the model also rewrote an existing file the task
  // didn't declare (e.g. adding a helper to a shared module that the in-scope files then import),
  // applying just the in-scope files leaves a broken tree that always fails validation and rolls
  // back. Refuse the whole task instead — a clean skip, no wasted validation run, tree untouched.
  // The prompt steers de-duplication toward NEW modules precisely so this refactor can still happen.
  if (outOfScope.length > 0) {
    return {
      taskId: task.id,
      edits: [],
      explanation: edit.explanation,
      sourceHashes,
      skip: `edit spans files outside the task's scope (${outOfScope.join(", ")}); skipped to avoid a partial change`,
    };
  }
  if (scoped.length === 0) {
    return {
      taskId: task.id,
      edits: [],
      explanation: edit.explanation,
      sourceHashes,
      skip: "model produced no in-scope edits",
    };
  }
  return { taskId: task.id, edits: scoped, explanation: edit.explanation, sourceHashes };
}

/** True if `rel` is a repo-relative path that stays inside the repo (no `..` / absolute escape). */
function withinRepo(root: string, rel: string): boolean {
  if (path.isAbsolute(rel)) return false;
  const relNorm = path.relative(root, path.resolve(root, rel));
  return relNorm !== "" && !relNorm.startsWith("..") && !path.isAbsolute(relNorm);
}

/**
 * Has any source file changed since the edit was generated? A parallel-generated edit
 * becomes stale if an earlier task in the same run touched one of its files; the engine
 * regenerates such edits against fresh content before applying them.
 */
export async function isStale(model: MentalModel, gen: GeneratedEdit): Promise<boolean> {
  for (const [rel, hash] of Object.entries(gen.sourceHashes)) {
    const content = await readFileSafe(model.root, rel);
    if (content === null || sha256(content) !== hash) return true;
  }
  return false;
}

/**
 * Review + Verify + Finalize (sequential): apply a generated edit to the working tree,
 * run the project's own validation, and either commit it or hard-reset the tree back to
 * where it started. Atomic and reversible; errors are never hidden.
 */
export async function applyEdit(
  model: MentalModel,
  task: Task,
  gen: GeneratedEdit,
  git: Git,
): Promise<TaskResult> {
  if (gen.skip || gen.edits.length === 0) {
    return {
      taskId: task.id,
      applied: false,
      committed: false,
      rolledBack: false,
      explanation: gen.explanation,
      error: gen.skip ?? "no edits",
    };
  }

  const before = await git.headSha();
  const changedFiles = gen.edits.map((e) => e.path);

  for (const e of gen.edits) {
    const abs = path.join(model.root, e.path);
    await fs.mkdir(path.dirname(abs), { recursive: true }); // support steps that create new files
    await fs.writeFile(abs, e.content, "utf8");
  }

  const validation = await validate(model.root, model.signals);
  if (!validation.ok) {
    await git.rollbackTo(before);
    return {
      taskId: task.id,
      applied: true,
      committed: false,
      rolledBack: true,
      validation,
      explanation: gen.explanation,
      error: "validation failed — rolled back",
      changedFiles,
    };
  }

  await git.stageAll();
  const commit = await git.commit(commitMessage(task, gen.explanation ?? ""));
  return {
    taskId: task.id,
    applied: true,
    committed: true,
    rolledBack: false,
    commit,
    validation,
    explanation: gen.explanation,
    changedFiles,
  };
}

/**
 * Execute a single task end to end (generate → apply). Used for the sequential path
 * and by callers that don't need the parallel split.
 */
export async function executeTask(
  model: MentalModel,
  task: Task,
  provider: ClaudeProvider,
  git: Git,
  opts: ExecuteOptions,
): Promise<TaskResult> {
  const gen = await generateEdit(model, task, provider, opts.conventions);
  if (opts.dryRun) {
    return {
      taskId: task.id,
      applied: false,
      committed: false,
      rolledBack: false,
      explanation: gen.explanation,
      error: gen.skip,
    };
  }
  return applyEdit(model, task, gen, git);
}

function buildEditPrompt(
  task: Task,
  files: Array<{ path: string; content: string }>,
  newFiles: string[],
  conventions?: string,
): string {
  const fileBlocks =
    files.length > 0
      ? files.map((f) => `=== FILE: ${f.path} ===\n${f.content}`).join("\n\n")
      : "(none — this task only creates new files)";
  const newFilesBlock = newFiles.length
    ? `\nFiles to CREATE (they do not exist yet — return their full contents):\n${newFiles
        .map((f) => `- ${f}`)
        .join("\n")}\n`
    : "";
  const conventionsBlock =
    conventions && conventions !== "No conventions learned yet."
      ? `\nProject conventions (match these exactly — do not reformat to a different style):\n${conventions}\n`
      : "";
  return `Task: ${task.title}
Why: ${task.rationale.why}
Goal: ${task.rationale.improves}
${conventionsBlock}${newFilesBlock}
Current file contents:
${fileBlocks}

Return JSON: { "explanation": string, "edits": [ { "path": string, "content": string } ] }
"content" must be the complete new file. Include every file you create or change.`;
}

export function commitMessage(task: Task, explanation: string): string {
  return [
    `orgit: ${task.title}`,
    "",
    explanation.trim(),
    "",
    `Why: ${task.rationale.why}`,
    `Improves: ${task.rationale.improves}`,
    `Impact: ${task.rationale.impact}`,
    "",
    "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>",
  ].join("\n");
}
